<?php
namespace Eike\Ride\Domain\Repository;

use TYPO3\CMS\Core\Configuration\ExtensionConfiguration;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Extbase\Persistence\QueryInterface;
use Undkonsorten\Addressmgmt\Domain\Repository\AddressRepository;

/***************************************************************
 *
 *  Copyright notice
 *
 *  (c) 2016 Eike Starkmann <eike.starkmann@posteo.de>
 *
 *  All rights reserved
 *
 *  This script is part of the TYPO3 project. The TYPO3 project is
 *  free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/

/**
 * The repository for Rides
 */
class RideRepository extends AddressRepository
{

    protected $defaultOrderings = [
        'date' => QueryInterface::ORDER_ASCENDING,
        'start.city' => QueryInterface::ORDER_ASCENDING
    ];

    public function findDemanded($addresses = NULL, $categories = NULL, $publishState = NULL, $orderings = null)
    {
        $settings = GeneralUtility::makeInstance(ExtensionConfiguration::class)->get('couch');
        if($settings['ignoreLanguages']){
            $query = $this->createQuery();
            $querySettings = $query->getQuerySettings();
            $querySettings->setRespectSysLanguage(false);
            $querySettings->setLanguageOverlayMode(true);
            $this->setDefaultQuerySettings($querySettings);
        }

        return parent::findDemanded($addresses, $categories, $publishState, $orderings); // TODO: Change the autogenerated stub
    }

}
